# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='nomination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollno', models.CharField(max_length=8, null=True)),
                ('name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[(b'Male', b'Male'), (b'Female', b'Female')], default=b'Male', max_length=20)),
                ('year', models.IntegerField(choices=[(1, b'I (Batch 2016-20)'), (2, b'II (Batch 2015-19)'), (3, b'III (Batch 2014-18)')], default=1)),
                ('branch', models.CharField(choices=[(b'Aeronautical Engineering', b'Aeronautical Engineering'), (b'Automobile Engineering', b'Automobile Engineering'), (b'Bio-Technology', b'Bio-Technology'), (b'Civil Engineering', b'Civil Engineering'), (b'Computer Applications', b'Computer Applications'), (b'Computer Science and Engineering', b'Computer Science and Engineering'), (b'Electrical and Electronics Engineering', b'Electrical and Electronics Engineering'), (b'Electronics and Communication Engineering', b'Electronics and Communication Engineering'), (b'Electronics and Instrumentation Engineering', b'Electronics and Instrumentation Engineering'), (b'Fashion Technology', b'Fashion Technology'), (b'Information Technology', b'Information Technology'), (b'Management Studies', b'Management Studies'), (b'Mechanical Engineering', b'Mechanical Engineering'), (b'Mechatronics Engineering', b'Mechatronics Engineering'), (b'Science and Humanities', b'Science and Humanities'), (b'Textile Technology', b'Textile Technology')], default=b'Aernonautical Engineering', max_length=255)),
                ('cgpa', models.CharField(default=0, max_length=4)),
                ('no_of_arrears', models.CharField(default=0, max_length=2)),
                ('history_of_arrears', models.CharField(default=0, max_length=2)),
                ('admission_type', models.CharField(choices=[(b'Counselling', b'Counselling'), (b'Management', b'Management')], default=b'Counselling', max_length=255)),
                ('area_of_residence', models.CharField(choices=[(b'Urban', b'Urban'), (b'Rural', b'Rural')], default=b'Urban', max_length=255)),
                ('type_of_entry', models.CharField(choices=[(b'Regular Entry', b'Regular Entry'), (b'Lateral Entry', b'Lateral Entry')], default=b'Regular Entry', max_length=255)),
                ('faced_disciplinary_action', models.CharField(choices=[(b'YES', b'YES'), (b'NO', b'NO')], default=b'NO', max_length=255)),
                ('mobile_No', models.CharField(help_text=b'Only 10 digits', max_length=10)),
                ('email_id', models.CharField(max_length=255)),
                ('req_posistion', models.CharField(choices=[(b'President', b'President/Vice President (Batch 2014-18)'), (b'Tresurer', b'Tresurer (Batch 2014-18)'), (b'Secretary', b'Secretary (Batch 2015-19)'), (b'Joint Secretary', b'Join Secretary (Batch 2016-20)')], max_length=255)),
                ('change_in_dept', models.TextField(max_length=255, null=True)),
                ('strengths', models.TextField(max_length=255, null=True)),
                ('reference1', models.CharField(max_length=255)),
                ('reference2', models.CharField(max_length=255)),
                ('class_advisor', models.CharField(max_length=255)),
                ('applied_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
