# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-03-02 07:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='nomination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollno', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=10)),
                ('gender', models.IntegerField(choices=[(0, 'Male'), (1, 'Female')])),
                ('year', models.IntegerField(choices=[(1, 'I'), (2, 'II'), (3, 'III'), (4, 'IV')], default=1)),
                ('branch', models.IntegerField(choices=[(0, 'Aeronautical Engineering'), (1, 'Automobile Engineering'), (2, 'Bio-Technology'), (3, 'Civil Engineering'), (4, 'Computer Applications'), (5, 'Computer Science and Engineering'), (6, 'Electrical and Electronics Engineering'), (7, 'Electronics and Communication Engineering'), (8, 'Electronics and Instrumentation Engineering'), (9, 'Fashion Technology'), (10, 'Information Technology'), (11, 'Management Studies'), (12, 'Mechanical Engineering'), (13, 'Mechatronics Engineering'), (14, 'Science and Humanities'), (15, 'Textile Technology')], default=0)),
                ('cgpa', models.FloatField(max_length=10)),
                ('no_of_arrears', models.IntegerField(max_length=10)),
                ('admission_type', models.BooleanField(choices=[(0, 'Counselling'), (1, 'Management')], default=0)),
                ('area_of_residence', models.BooleanField(choices=[(0, 'Urban'), (1, 'Rural')], default=0)),
                ('type_of_entry', models.BooleanField(choices=[(0, 'Regular Entry'), (1, 'Lateral Entry')], default=0)),
                ('faced_disciplinary_action', models.BooleanField(choices=[(0, 'YES'), (1, 'NO')], default=0)),
                ('mobile_No', models.CharField(max_length=10)),
                ('email_id', models.CharField(max_length=100)),
                ('req_posistion', models.CharField(max_length=25)),
                ('change_in_dept1', models.CharField(max_length=255)),
                ('change_in_dept2', models.CharField(max_length=255)),
                ('strength1', models.CharField(max_length=255)),
                ('strength2', models.CharField(max_length=255)),
                ('reference1', models.CharField(max_length=25)),
                ('reference2', models.CharField(max_length=25)),
                ('class_advisor', models.CharField(max_length=25)),
                ('hod', models.CharField(max_length=25)),
            ],
        ),
    ]
