# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-03-02 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('da', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomination',
            name='mobile_No',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='nomination',
            name='no_of_arrears',
            field=models.IntegerField(),
        ),
    ]
