# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-03-02 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('da', '0002_auto_20170302_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nomination',
            name='change_in_dept1',
        ),
        migrations.RemoveField(
            model_name='nomination',
            name='change_in_dept2',
        ),
        migrations.AddField(
            model_name='nomination',
            name='change_in_dept',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
