# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-03-02 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('da', '0007_nomination_rollno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomination',
            name='branch',
            field=models.CharField(choices=[('Aeronautical Engineering', 'Aeronautical Engineering'), ('Automobile Engineering', 'Automobile Engineering'), ('Bio-Technology', 'Bio-Technology'), ('Civil Engineering', 'Civil Engineering'), ('Computer Applications', 'Computer Applications'), ('Computer Science and Engineering', 'Computer Science and Engineering'), ('Electrical and Electronics Engineering', 'Electrical and Electronics Engineering'), ('Electronics and Communication Engineering', 'Electronics and Communication Engineering'), ('Electronics and Instrumentation Engineering', 'Electronics and Instrumentation Engineering'), ('Fashion Technology', 'Fashion Technology'), ('Information Technology', 'Information Technology'), ('Management Studies', 'Management Studies'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Mechatronics Engineering', 'Mechatronics Engineering'), ('Science and Humanities', 'Science and Humanities'), ('Textile Technology', 'Textile Technology')], default='Aernonautical Engineering', max_length=255),
        ),
        migrations.AlterField(
            model_name='nomination',
            name='cgpa',
            field=models.FloatField(max_length=255),
        ),
        migrations.AlterField(
            model_name='nomination',
            name='class_advisor',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='nomination',
            name='email_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='nomination',
            name='hod',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='nomination',
            name='mobile_No',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='nomination',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='nomination',
            name='reference1',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='nomination',
            name='reference2',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='nomination',
            name='reference3',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='nomination',
            name='req_posistion',
            field=models.CharField(max_length=255),
        ),
    ]
