# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-03-02 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('da', '0009_auto_20170302_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomination',
            name='mobile_No',
            field=models.CharField(help_text='Only 10 digits', max_length=10),
        ),
    ]
