# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-03-02 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('da', '0011_auto_20170302_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nomination',
            name='hod',
        ),
        migrations.AlterField(
            model_name='nomination',
            name='req_posistion',
            field=models.CharField(choices=[('President', 'President/Vice President (Batch 2014-18)'), ('Tresurer', 'Tresurer (Batch 2014-18)'), ('Secretary', 'Secretary (Batch 2015-19)'), ('Joint Secretary', 'Join Secretary (Batch 2016-20)')], max_length=255),
        ),
        migrations.AlterField(
            model_name='nomination',
            name='year',
            field=models.IntegerField(choices=[(1, 'I (Batch 2016-20)'), (2, 'II (Batch 2015-19)'), (3, 'III (Batch 2014-18)')], default=1),
        ),
    ]
