# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-03-02 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('da', '0012_auto_20170302_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomination',
            name='applied_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
