# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-03-02 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('da', '0013_nomination_applied_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomination',
            name='admission_type',
            field=models.CharField(choices=[('Counselling', 'Counselling'), ('Management', 'Management')], default='Counselling', max_length=255),
        ),
        migrations.AlterField(
            model_name='nomination',
            name='area_of_residence',
            field=models.CharField(choices=[('Urban', 'Urban'), ('Rural', 'Rural')], default='Urban', max_length=255),
        ),
        migrations.AlterField(
            model_name='nomination',
            name='faced_disciplinary_action',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='NO', max_length=255),
        ),
        migrations.AlterField(
            model_name='nomination',
            name='type_of_entry',
            field=models.CharField(choices=[('Regular Entry', 'Regular Entry'), ('Lateral Entry', 'Lateral Entry')], default='Regular Entry', max_length=255),
        ),
    ]
