# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('da', '0014_auto_20170303_0258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomination',
            name='cgpa',
            field=models.FloatField(max_length=3),
        ),
        migrations.AlterField(
            model_name='nomination',
            name='gender',
            field=models.IntegerField(choices=[(0, b'Male'), (1, b'Female')], default=0),
        ),
        migrations.AlterField(
            model_name='nomination',
            name='rollno',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
