# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('da', '0016_nomination_history_of_arrears'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomination',
            name='gender',
            field=models.IntegerField(choices=[(b'Male', b'Male'), (b'Female', b'Female')], default=b'Male'),
        ),
        migrations.AlterField(
            model_name='nomination',
            name='history_of_arrears',
            field=models.IntegerField(default=0),
        ),
    ]
