# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('da', '0017_auto_20170304_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomination',
            name='gender',
            field=models.CharField(choices=[(b'Male', b'Male'), (b'Female', b'Female')], default=b'Male', max_length=20),
        ),
    ]
