# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('da', '0018_auto_20170306_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomination',
            name='history_of_arrears',
            field=models.CharField(default=0, max_length=2),
        ),
        migrations.AlterField(
            model_name='nomination',
            name='no_of_arrears',
            field=models.CharField(default=0, max_length=2),
        ),
    ]
