# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('da', '0019_auto_20170306_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomination',
            name='cgpa',
            field=models.CharField(max_length=3),
        ),
    ]
