# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('da', '0021_auto_20170306_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomination',
            name='cgpa',
            field=models.CharField(default=0, max_length=4),
        ),
    ]
